name: assorted_layout_widgets
description: ColumnSuper, RowSuper, FitHorizontally, Box, WrapSuper, TextOneLine, Delayed, Pad, ButtonBarSuper, NormalizedOverflowBox, showDialogSuper.
version: 5.0.0
author: Marcelo Glasberg <marcglasberg@gmail.com>
homepage: https://github.com/marcglasberg/assorted_layout_widgets

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  matrix4_transform: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.16.5

flutter:
